version: '3'

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  django-stanovi-api:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django-stanovi-api
    container_name: django-stanovi-api
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres-stanovi-api
    container_name: postgres-stanovi-api
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres


  pgadmin-stanovi-api:
    container_name: pgadmin4-stanovi-api
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dejan.cugalj@factoryww.com
      PGADMIN_DEFAULT_PASSWORD: ds241165A!
    ports:
      - "5050:80"
