# Generated by Django 3.2.8 on 2022-01-31 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kupci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stanovi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponude',
            fields=[
                ('id_ponude', models.BigAutoField(primary_key=True, serialize=False)),
                ('cena_stana_za_kupca', models.FloatField(default=0, verbose_name='Cena stana za kupca')),
                ('napomena', models.CharField(blank=True, default='', max_length=252, verbose_name='Napomena')),
                ('broj_ugovora', models.CharField(blank=True, max_length=252, null=True, unique=True, verbose_name='Broj Ugovora')),
                ('datum_ugovora', models.DateField(blank=True, null=True, verbose_name='Datum Ponude')),
                ('status_ponude', models.CharField(choices=[('potencijalan', 'Potencijalan'), ('rezervisan', 'Rezervisan'), ('kupljen', 'Kupljen')], default='potencijalan', max_length=20)),
                ('nacin_placanja', models.CharField(choices=[('ceo_iznos', 'Placanje u celosti'), ('kredit', 'Kreditom'), ('na_rate', 'Na rate'), ('ucesce', 'Učešće')], default='ceo_iznos', max_length=30, verbose_name='Nacin Placanja')),
                ('odobrenje', models.BooleanField(default=False, verbose_name='Odobrenje')),
                ('klijent_prodaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kupac', models.ForeignKey(db_column='id_kupca', on_delete=django.db.models.deletion.CASCADE, related_name='lista_ponuda_kupca', to='kupci.kupci')),
                ('stan', models.ForeignKey(db_column='id_stana', on_delete=django.db.models.deletion.CASCADE, related_name='lista_ponuda_stana', to='stanovi.stanovi')),
            ],
            options={
                'verbose_name': 'Ponuda Kupcima',
                'verbose_name_plural': 'Ponude Kupcima',
                'db_table': 'ponude',
                'ordering': ['-id_ponude'],
            },
        ),
    ]
