# Generated by Django 3.2.8 on 2021-10-24 02:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stanovi', '0001_initial'),
        ('kupci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponude',
            fields=[
                ('id_ponude', models.BigAutoField(primary_key=True, serialize=False)),
                ('cena_stana_za_kupca', models.PositiveIntegerField(default=0, verbose_name='Cena stana za kupca')),
                ('napomena', models.CharField(blank=True, default='', max_length=252)),
                ('broj_ugovora', models.CharField(blank=True, default='', max_length=252)),
                ('datum_ugovora', models.DateField(default=django.utils.timezone.now)),
                ('status_ponude', models.CharField(choices=[('potencijalan', 'Potencijalan'), ('rezervisan', 'Rezervisan'), ('kupljen', 'Kupljen')], default='potencijalan', max_length=20)),
                ('nacin_placanja', models.CharField(choices=[('ceo_iznos', 'Placanje u celosti'), ('kredit', 'Kreditom'), ('na_rate', 'Na rate'), ('ucesce', 'Učešće')], default='ceo_iznos', max_length=30)),
                ('kupac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kupci.kupci')),
                ('stan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stanovi.stanovi')),
            ],
            options={
                'verbose_name': 'Ponuda Kupcima',
                'verbose_name_plural': 'Ponude Kupcima',
                'db_table': 'ponude',
            },
        ),
    ]
