# Generated by Django 3.2.8 on 2021-12-12 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ponude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponude',
            name='datum_ugovora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
