# Generated by Django 3.2.8 on 2021-12-12 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ponude', '0002_alter_ponude_datum_ugovora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponude',
            name='datum_ugovora',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
