# Generated by Django 3.2.8 on 2022-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzuriranjeCena',
            fields=[
                ('id_azur_cene', models.BigAutoField(primary_key=True, serialize=False)),
                ('sprat', models.CharField(default='1', max_length=10, verbose_name='Sprat stana')),
                ('broj_soba', models.FloatField(default=1, verbose_name='Broj soba stana')),
                ('orijentisanost', models.CharField(blank=True, choices=[('Sever', 'Sever'), ('Jug', 'Jug'), ('Istok', 'Istok'), ('Zapad', 'Zapad')], default='Jug', max_length=20, null=True)),
                ('cena_kvadrata', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena kvadrata')),
            ],
            options={
                'verbose_name': 'AzuriranjeCena',
                'verbose_name_plural': 'AzuriranjeCena',
                'db_table': 'azuriranje_cena',
            },
        ),
        migrations.CreateModel(
            name='Stanovi',
            fields=[
                ('id_stana', models.BigAutoField(primary_key=True, serialize=False)),
                ('lamela', models.CharField(default='', max_length=50, unique=True, verbose_name='Lamela')),
                ('adresa_stana', models.CharField(default='', max_length=254, verbose_name='Adresa stana')),
                ('kvadratura', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Kvadratura stana')),
                ('kvadratura_korekcija', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Korekcija kvadrature')),
                ('iznos_za_korekciju_kvadrature', models.DecimalField(decimal_places=2, default=0.97, max_digits=3, verbose_name='Iznos za korekciju kvadrature')),
                ('sprat', models.CharField(default='1', max_length=10, verbose_name='Sprat stana')),
                ('broj_soba', models.FloatField(default=1, verbose_name='Broj soba stana')),
                ('orijentisanost', models.CharField(blank=True, choices=[('Sever', 'Sever'), ('Jug', 'Jug'), ('Istok', 'Istok'), ('Zapad', 'Zapad')], default='Jug', max_length=20, null=True)),
                ('broj_terasa', models.PositiveIntegerField(default=0, verbose_name='Broj terasa stana')),
                ('cena_stana', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena stana')),
                ('cena_kvadrata', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cena kvadrata')),
                ('napomena', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Napomena')),
                ('status_prodaje', models.CharField(choices=[('dostupan', 'Dostupan'), ('rezervisan', 'Rezervisan'), ('prodat', 'Prodat')], default='dostupan', max_length=20)),
            ],
            options={
                'verbose_name': 'Stan',
                'verbose_name_plural': 'Stanovi',
                'db_table': 'stanovi',
            },
        ),
    ]
