# Generated by Django 3.2.8 on 2021-11-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanovi',
            fields=[
                ('id_stana', models.BigAutoField(primary_key=True, serialize=False)),
                ('lamela', models.CharField(default=0, max_length=50, verbose_name='Lamela')),
                ('adresa_stana', models.CharField(default='', max_length=254, verbose_name='Adresa stana')),
                ('kvadratura', models.PositiveIntegerField(default=0, verbose_name='Kvadratura stana')),
                ('sprat', models.PositiveIntegerField(default=1, verbose_name='Sprat stana')),
                ('broj_soba', models.PositiveIntegerField(default=1, verbose_name='Broj soba stana')),
                ('orijentisanost', models.CharField(blank=True, choices=[('Sever', 'Sever'), ('Jug', 'Jug'), ('Istok', 'Istok'), ('Zapad', 'Zapad')], default='Sever', max_length=20, null=True)),
                ('broj_terasa', models.PositiveIntegerField(default=0, verbose_name='Broj terasa stana')),
                ('cena_stana', models.PositiveIntegerField(default=0, verbose_name='Cena stana')),
                ('cena_stana_za_kupca', models.PositiveIntegerField(default=0, verbose_name='Cena stana za kupca')),
                ('napomena', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Napomena')),
                ('status_prodaje', models.CharField(choices=[('dostupan', 'Dostupan'), ('rezervisan', 'Rezervisan'), ('prodat', 'Prodat')], default='dostupan', max_length=20)),
                ('klijent_prodaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stan',
                'verbose_name_plural': 'Stanovi',
                'db_table': 'stanovi',
            },
        ),
    ]
