# Generated by Django 3.2.8 on 2021-10-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlikeSTana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika_stana', models.ImageField(blank=True, default='images/default.png', help_text='Molimo da dodate sliku', null=True, upload_to='images/', verbose_name='Slika_Stana')),
                ('alt_text', models.CharField(blank=True, help_text='Molimo da dodate sliku', max_length=255, null=True, verbose_name='Alternativni Text')),
                ('stan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slike_stana', to='stanovi.stanovi')),
            ],
        ),
    ]
