# Generated by Django 3.2.8 on 2021-10-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0002_slikestana'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slikestana',
            options={'verbose_name': 'slike_stana', 'verbose_name_plural': 'slike_stanova'},
        ),
        migrations.AlterModelTable(
            name='slikestana',
            table='slike_stana',
        ),
    ]
