# Generated by Django 3.2.8 on 2021-10-23 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0003_auto_20211023_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='slikestana',
            name='kreirana',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slikestana',
            name='ucitana',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
