# Generated by Django 3.2.8 on 2021-10-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0004_auto_20211023_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slikestana',
            old_name='slika_stana',
            new_name='slike_stana',
        ),
    ]
