# Generated by Django 3.2.8 on 2021-10-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0005_rename_slika_stana_slikestana_slike_stana'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlikeSTana',
            new_name='SlikaStana',
        ),
        migrations.AlterModelOptions(
            name='slikastana',
            options={'verbose_name': 'slika_stana', 'verbose_name_plural': 'slike_stanova'},
        ),
        migrations.RenameField(
            model_name='slikastana',
            old_name='slike_stana',
            new_name='slika_stana',
        ),
        migrations.AlterModelTable(
            name='slikastana',
            table='slika_stana',
        ),
    ]
