# Generated by Django 3.2.8 on 2021-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stanovi', '0006_auto_20211023_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanovi',
            name='orijentisanost',
            field=models.CharField(blank=True, choices=[('Sever', 'Sever'), ('Jug', 'Jug'), ('Istok', 'Istok'), ('Zapad', 'Zapad')], default='Sever', max_length=20, null=True),
        ),
    ]
