# Generated by Django 3.2.8 on 2022-01-31 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garaze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarazePonude',
            fields=[
                ('id_ponude_garaze', models.BigAutoField(primary_key=True, serialize=False)),
                ('cena_garaze_za_kupca', models.FloatField(default=0, verbose_name='Cena Garaze za kupca')),
                ('napomena_ponude_garaze', models.CharField(blank=True, default='Nema Napomene', max_length=252, verbose_name='Napomena Garaze')),
                ('broj_ugovora_garaze', models.CharField(blank=True, max_length=252, null=True, unique=True, verbose_name='Broj Ugovora Garaze')),
                ('datum_ugovora_garaze', models.DateField(blank=True, null=True, verbose_name='Datum Ponude Garaze')),
                ('status_ponude_garaze', models.CharField(choices=[('dostupna', 'Dostupna'), ('rezervisana', 'Rezervisana'), ('prodata', 'Prodata')], default='dostupna', max_length=20)),
                ('nacin_placanja_garaze', models.CharField(choices=[('ceo_iznos', 'Placanje u celosti'), ('kredit', 'Kreditom'), ('na_rate', 'Na rate'), ('ucesce', 'Učešće')], default='ceo_iznos', max_length=30, verbose_name='Nacin Placanja Garaze')),
                ('odobrenje_ponude_garaze', models.BooleanField(default=False, verbose_name='Odobrenje Ponude Garaze')),
                ('garaza', models.ForeignKey(db_column='jedinstveni_broj_garaze', on_delete=django.db.models.deletion.CASCADE, related_name='lista_ponuda_garaza', to='garaze.garaze')),
            ],
            options={
                'verbose_name': 'Ponuda Kupcima Garaze',
                'verbose_name_plural': 'Ponude Kupcima Garaze',
                'db_table': 'ponude_garaze',
                'ordering': ['-id_ponude_garaze'],
            },
        ),
    ]
