# Generated by Django 3.2.8 on 2022-01-31 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kupci', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garaze_ponude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garazeponude',
            name='klijent_prodaje_garaze',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='garazeponude',
            name='kupac_garaze',
            field=models.ForeignKey(db_column='id_kupca', on_delete=django.db.models.deletion.CASCADE, related_name='lista_ponuda_kupca_garaza', to='kupci.kupci'),
        ),
    ]
