# Generated by Django 3.2.8 on 2021-10-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kupci',
            fields=[
                ('id_kupca', models.BigAutoField(primary_key=True, serialize=False)),
                ('lice', models.CharField(choices=[('Fizicko', 'Fizicko Lice'), ('Pravno', 'Pravno Lice')], default='Fizicko Lice', max_length=20)),
                ('ime_prezime', models.CharField(max_length=50, verbose_name='Ime i prezime Kupca')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Kupca')),
                ('broj_telefona', models.CharField(max_length=20, verbose_name='Broj telefona')),
                ('Jmbg_Pib', models.IntegerField(verbose_name='JMBG ili PIB')),
                ('adresa', models.CharField(max_length=50, verbose_name='Adresa')),
            ],
            options={
                'verbose_name': 'Kupac',
                'verbose_name_plural': 'Kupci',
                'db_table': 'kupci',
            },
        ),
    ]
