# Generated by Django 3.2.8 on 2022-01-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garaze',
            fields=[
                ('id_garaze', models.BigAutoField(primary_key=True, serialize=False)),
                ('jedinstveni_broj_garaze', models.PositiveIntegerField(unique=True, verbose_name='Broj Garaze')),
                ('cena_garaze', models.FloatField(default=0.0, verbose_name='Cena Garaze')),
                ('napomena_garaze', models.CharField(blank=True, default='Nema Napomene', max_length=250, null=True, verbose_name='Napomena')),
                ('status_prodaje_garaze', models.CharField(choices=[('dostupna', 'Dostupna'), ('rezervisana', 'Rezervisana'), ('prodata', 'Prodata')], default='dostupna', max_length=20)),
            ],
            options={
                'verbose_name': 'Garaze',
                'verbose_name_plural': 'Garaze',
                'db_table': 'garaze',
                'ordering': ['-jedinstveni_broj_garaze'],
            },
        ),
    ]
