# Generated by Django 3.2.8 on 2021-10-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnici',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='korisnici',
            name='is_finansije',
        ),
        migrations.RemoveField(
            model_name='korisnici',
            name='is_prodavac',
        ),
        migrations.AddField(
            model_name='korisnici',
            name='role',
            field=models.CharField(choices=[('Prodavac', 'Prodavac'), ('Finansije', 'Finansije'), ('Administrator', 'Administrator')], default='Administrator', max_length=40),
        ),
    ]
