# Generated by Django 3.2.8 on 2021-11-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnici',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='korisnici',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='korisnici',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='korisnici',
            name='username',
        ),
    ]
