# Generated by Django 3.2.8 on 2021-11-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0002_auto_20211128_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnici',
            old_name='user_name',
            new_name='username',
        ),
    ]
